"""
Import converted ROSE Online terrain files (block_X_Y.mesh.bin format).

This plugin imports the converted terrain files generated by the rose-zone-converter tool.
The converted format simplifies loading by providing:
- Pre-baked albedo textures
- Generated normal maps
- Binary mesh data with positions, normals, UVs, tangents, and indices

Binary format (from README):
- [u32 vertex_count]
- [positions: [f32; 3] * vertex_count]
- [normals: [f32; 3] * vertex_count]
- [uvs: [f32; 2] * vertex_count]
- [u32 has_tangents] (1 or 0)
- [tangents: [f32; 4] * vertex_count] (if has_tangents == 1)
- [u32 index_count]
- [indices: u32 * index_count]
"""

from pathlib import Path
import struct
import bpy
from bpy.props import StringProperty, BoolProperty, IntProperty
from bpy_extras.io_utils import ImportHelper


class ImportConvertedTerrain(bpy.types.Operator, ImportHelper):
    """Import converted ROSE terrain files (block_X_Y.mesh.bin)"""
    bl_idname = "import_converted_terrain.mesh_bin"
    bl_label = "Import Converted ROSE Terrain (.mesh.bin)"
    bl_options = {"PRESET"}

    filename_ext = ".mesh.bin"
    filter_glob: StringProperty(
        default="*.mesh.bin",
        options={"HIDDEN"}
    )
    
    # Custom file filter for the file browser
    files: bpy.props.CollectionProperty(type=bpy.types.OperatorFileListElement)
    directory: bpy.props.StringProperty()

    load_normal_map: BoolProperty(
        name="Load Normal Map",
        description="Load the generated normal map if available",
        default=True,
    )

    merge_blocks: BoolProperty(
        name="Merge All Blocks",
        description="Merge all terrain blocks in the directory into a single mesh",
        default=False,
    )

    def load_mesh_binary(self, filepath):
        """
        Load the binary mesh file.
        
        Returns:
            dict with 'positions', 'normals', 'uvs', 'tangents' (optional), 'indices'
        """
        mesh_data = {}
        
        with open(filepath, 'rb') as f:
            # Read vertex count (u32)
            vertex_count = struct.unpack('<I', f.read(4))[0]
            
            # Read positions (f32 x 3 per vertex)
            positions = []
            for _ in range(vertex_count):
                x, y, z = struct.unpack('<fff', f.read(12))
                positions.append((x, y, z))
            
            # Read normals (f32 x 3 per vertex)
            normals = []
            for _ in range(vertex_count):
                x, y, z = struct.unpack('<fff', f.read(12))
                normals.append((x, y, z))
            
            # Read UVs (f32 x 2 per vertex)
            uvs = []
            for _ in range(vertex_count):
                u, v = struct.unpack('<ff', f.read(8))
                # UVs are used as-is from the converter (matching Rust implementation)
                # Both Bevy and Blender use same UV convention: (0,0)=bottom-left, (1,1)=top-right
                uvs.append((u, v))
            
            # Read has_tangents flag (u32)
            has_tangents = struct.unpack('<I', f.read(4))[0]
            
            # Read tangents if present (f32 x 4 per vertex)
            tangents = None
            if has_tangents:
                tangents = []
                for _ in range(vertex_count):
                    x, y, z, w = struct.unpack('<ffff', f.read(16))
                    tangents.append((x, y, z, w))
            
            # Read index count (u32)
            index_count = struct.unpack('<I', f.read(4))[0]
            
            # Read indices (u32 per index)
            indices = []
            for _ in range(index_count):
                idx = struct.unpack('<I', f.read(4))[0]
                indices.append(idx)
        
        mesh_data['positions'] = positions
        mesh_data['normals'] = normals
        mesh_data['uvs'] = uvs
        mesh_data['tangents'] = tangents
        mesh_data['indices'] = indices
        mesh_data['vertex_count'] = vertex_count
        mesh_data['index_count'] = index_count
        
        return mesh_data

    def create_material(self, block_name, albedo_path, normal_path=None):
        """
        Create a PBR material with albedo and optional normal map.
        
        Args:
            block_name: Name for the material
            albedo_path: Path to the albedo texture
            normal_path: Optional path to the normal map
            
        Returns:
            Blender material or None if creation failed
        """
        try:
            mat = bpy.data.materials.new(name=f"ROSE_Converted_{block_name}")
            mat.use_nodes = True
            
            # CRITICAL: Terrain must be OPAQUE to match Rust implementation (zone_loader.rs line 3391-3398)
            # The baked albedo is fully opaque - transparency was handled during baking by alpha blending layers
            mat.blend_method = 'OPAQUE'  # Use opaque rendering like the game client
            
            nodes = mat.node_tree.nodes
            links = mat.node_tree.links
            
            nodes.clear()
            
            # Albedo texture node
            albedo_node = nodes.new(type='ShaderNodeTexImage')
            albedo_node.location = (-600, 100)
            albedo_image = bpy.data.images.load(albedo_path)
            albedo_node.image = albedo_image
            
            # Principled BSDF
            bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
            bsdf.location = (0, 0)
            # Set default PBR values (Blender 4.x uses different input names)
            # Roughness is input index 9, Metallic is input index 10
            if 'Roughness' in bsdf.inputs:
                bsdf.inputs['Roughness'].default_value = 0.8
            elif len(bsdf.inputs) > 9:
                bsdf.inputs[9].default_value = 0.8
            if 'Metallic' in bsdf.inputs:
                bsdf.inputs['Metallic'].default_value = 0.0
            elif len(bsdf.inputs) > 10:
                bsdf.inputs[10].default_value = 0.0
            
            # Material Output
            output = nodes.new(type='ShaderNodeOutputMaterial')
            output.location = (400, 0)
            
            # Connect albedo color to base color
            links.new(albedo_node.outputs["Color"], bsdf.inputs["Base Color"])
            # Note: No alpha connection needed - terrain is opaque like in the game client
            links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])
            
            # Add normal map if available
            if normal_path and self.load_normal_map and Path(normal_path).exists():
                normal_node = nodes.new(type='ShaderNodeTexImage')
                normal_node.location = (-600, -100)
                normal_image = bpy.data.images.load(normal_path)
                
                # CRITICAL: Normal maps must use Non-Color color space (not sRGB)
                # This matches the Rust implementation where settings.is_srgb = false
                normal_image.colorspace_settings.name = 'Non-Color'
                
                normal_node.image = normal_image
                
                normal_map_node = nodes.new(type='ShaderNodeNormalMap')
                normal_map_node.location = (-200, -100)
                
                # Blender 4.x uses "Color" input for normal map (not "Height")
                # Input 0 = Strength, Input 1 = Color
                links.new(normal_node.outputs["Color"], normal_map_node.inputs["Color"])
                links.new(normal_map_node.outputs["Normal"], bsdf.inputs["Normal"])
            
            return mat
        except Exception as e:
            self.report({'ERROR'}, f"Failed to create material: {str(e)}")
            return None

    def create_mesh_from_data(self, mesh_data, block_name, context):
        """
        Create a Blender mesh from the parsed mesh data.

        Positions are converted Bevy Y-up -> Blender Z-up only; world
        placement comes from the per-block offsets (merge path) or the
        object location (separate path), never from an extra parameter.

        Args:
            mesh_data: Dictionary with positions, normals, uvs, tangents, indices
            block_name: Name for the mesh object
            context: Blender context (needed for operations)

        Returns:
            Blender mesh object
        """
        # Create mesh
        mesh = bpy.data.meshes.new(name=f"ROSE_Terrain_{block_name}")
        obj = bpy.data.objects.new(f"ROSE_Terrain_{block_name}", mesh)
        
        # Get collections
        terrain_collection = bpy.data.collections.get("ROSE_Terrain")
        if not terrain_collection:
            terrain_collection = bpy.data.collections.new("ROSE_Terrain")
            context.scene.collection.children.link(terrain_collection)
        
        terrain_collection.objects.link(obj)
        
        # Convert positions to Blender coordinates
        # The converted terrain files are in Bevy's Y-up format:
        #   - X: horizontal (east/west)
        #   - Y: height (up/down)
        #   - Z: depth (north/south)
        # Blender uses Z-up format:
        #   - X: horizontal (east/west)
        #   - Y: depth (north/south)
        #   - Z: height (up/down)
        # So we need to swap Y and Z to convert from Bevy to Blender
        blender_positions = []
        for x, y, z in mesh_data['positions']:
            # Convert from Bevy (Y-up) to Blender (Z-up)
            # Bevy: X, Y (height), Z (depth)
            # Blender: X, Y (depth), Z (height)
            blender_x = x
            blender_y = z  # Bevy Z (depth) becomes Blender Y
            blender_z = y  # Bevy Y (height) becomes Blender Z
            blender_positions.append((blender_x, blender_y, blender_z))
        
        # Convert normals to Blender coordinates
        # Same Y/Z swap as positions
        blender_normals = []
        for x, y, z in mesh_data['normals']:
            # Bevy normal (x, y_height, z_depth) -> Blender normal (x, z_depth, y_height)
            blender_normals.append((x, z, y))
        
        # Create vertices
        # Convert flat index list to triangles (groups of 3)
        indices = mesh_data['indices']
        triangles = []
        for i in range(0, len(indices), 3):
            if i + 2 < len(indices):
                triangles.append((indices[i], indices[i+1], indices[i+2]))
        
        mesh.from_pydata(blender_positions, [], triangles)
        
        # Normals will be calculated automatically by Blender when needed
        # For now, let Blender handle it
        
        # Add UV layer
        if mesh_data['uvs']:
            uv_layer = mesh.uv_layers.new(name="UVMap")
            # UVs are stored per-vertex in the original data
            # After from_pydata, we need to map each loop to its vertex's UV
            for loop_idx in range(len(mesh.loops)):
                vertex_idx = mesh.loops[loop_idx].vertex_index
                if vertex_idx < len(mesh_data['uvs']):
                    uv_layer.data[loop_idx].uv = mesh_data['uvs'][vertex_idx]
        
        # Add tangent data if available (Blender 4.x uses attributes)
        if mesh_data['tangents']:
            # Blender calculates tangents automatically when normal map is used
            # We can set them via attributes if needed
            if "Tangent" not in mesh.attributes:
                mesh.attributes.new("Tangent", 'FLOAT_VECTOR', 'POINT')
            tangent_attr = mesh.attributes["Tangent"]
            for i, tangent in enumerate(mesh_data['tangents']):
                if i < len(tangent_attr.data):
                    tangent_attr.data[i].vector = tangent[:3]  # Use XYZ, ignore W
        
        return obj

    def execute(self, context):
        import time
        start_time = time.time()
        
        wm = context.window_manager
        wm.progress_begin(0, 100)
        
        try:
            # CRITICAL FIX: Handle multi-file selection from file browser
            # When multiple files are selected, self.files contains all of them
            # Otherwise fall back to single file mode using self.filepath
            if len(self.files) > 0:
                # Multi-file selection mode - each file gets its own material
                directory = Path(self.directory).resolve() if self.directory else None
                block_files = []
                for f in self.files:
                    if directory and f.name != "":  # Skip empty filenames
                        block_files.append(directory / f.name)
            else:
                # Single file mode (backward compatibility)
                filepath = Path(self.filepath).resolve()
                directory = filepath.parent
                block_files = [filepath]
            
            if not block_files:
                self.report({'ERROR'}, "No files selected")
                return {'CANCELLED'}
            
            # Disable viewport updates for performance
            try:
                original_use_autopersist = bpy.context.preferences.view.use_auto_persist
                bpy.context.preferences.view.use_auto_persist = False
            except:
                pass
            
            created_objects = []
            
            if self.merge_blocks:
                # Load all blocks in the directory
                wm.progress_update(10)
                block_files = sorted(directory.glob("block_*.mesh.bin"))
                
                if not block_files:
                    self.report({'ERROR'}, "No block files found in directory")
                    return {'CANCELLED'}
                
                total_blocks = len(block_files)
                all_positions = []
                all_normals = []
                all_uvs = []
                all_tangents = []
                all_indices = []
                vertex_offset = 0
                
                # Find the first albedo and normal for material
                first_albedo = None
                first_normal = None
                
                for idx, block_file in enumerate(block_files):
                    wm.progress_update(20 + (idx * 60 // total_blocks))
                    
                    # Load mesh data
                    mesh_data = self.load_mesh_binary(str(block_file))
                    
                    # Store texture paths from first block
                    if first_albedo is None:
                        # Handle filenames like "block_31_30.mesh.bin" - stem gives "block_31_30.mesh"
                        stem = block_file.stem
                        if stem.endswith('.mesh'):
                            stem = stem[:-5]  # Remove ".mesh" suffix
                        first_albedo = block_file.with_name(f"{stem}_albedo.png")
                        first_normal = block_file.with_name(f"{stem}_normal.png")
                        self.report({'INFO'}, f"Looking for albedo at: {first_albedo}")
                        self.report({'INFO'}, f"Albedo exists: {first_albedo.exists()}")
                    
                    # Offset positions for merging
                    # Each block is 65x65 vertices, need to calculate offset based on block coordinates
                    # Handle filenames like "block_31_30.mesh.bin" - stem gives "block_31_30.mesh"
                    block_name = block_file.stem  # e.g., "block_31_30.mesh"
                    # Remove .mesh if present (from .mesh.bin extension)
                    if block_name.endswith('.mesh'):
                        block_name = block_name[:-5]  # Remove ".mesh" suffix
                    
                    parts = block_name.split('_')
                    if len(parts) >= 3:
                        try:
                            block_x = int(parts[1])
                            block_y = int(parts[2])
                            # CRITICAL: Match Rust implementation exactly (zone_loader.rs lines 3317-3318)
                            # Rust uses: offset_x = 160.0 * block_x, offset_y = 160.0 * (65.0 - block_y)
                            # The Y-axis is inverted because Bevy's coordinate system differs from Blender's
                            rust_offset_x = 160.0 * block_x
                            rust_offset_y = 160.0 * (65.0 - block_y)
                            
                            # Apply world centering like Rust does: Transform::from_xyz(offset_x - 5200.0, 0.0, -offset_y + 5200.0)
                            # In Blender Z-up system: X stays same, Bevy Z (depth) becomes Y, Bevy Y (height) becomes Z
                            offset_x = rust_offset_x - 5200.0
                            offset_y = -rust_offset_y + 5200.0
                        except ValueError:
                            self.report({'WARNING'}, f"Could not parse block coordinates from {block_name}")
                            offset_x = 0
                            offset_y = 0
                    else:
                        self.report({'WARNING'}, f"Invalid block name format: {block_name}")
                        offset_x = 0
                        offset_y = 0
                    
                    # Apply offset to positions
                    # CRITICAL: In merge_blocks mode, do NOT apply world_offset
                    # The offset calculation already includes proper centering (-5200.0/+5200.0)
                    # Applying world_offset would cause double transformation and incorrect positioning
                    offset_positions = []
                    for x, y, z in mesh_data['positions']:
                        blender_x = x + offset_x
                        blender_y = z + offset_y  # Bevy Z (depth) becomes Blender Y
                        blender_z = y  # Bevy Y (height) becomes Blender Z
                        offset_positions.append((blender_x, blender_y, blender_z))
                    
                    all_positions.extend(offset_positions)
                    # Transform normals: swap Y and Z (Bevy Y-up to Blender Z-up)
                    transformed_normals = []
                    for x, y, z in mesh_data['normals']:
                        transformed_normals.append((x, z, y))
                    all_normals.extend(transformed_normals)
                    all_uvs.extend(mesh_data['uvs'])
                    
                    if mesh_data['tangents']:
                        all_tangents.extend(mesh_data['tangents'])
                    
                    # Offset indices
                    offset_indices = [i + vertex_offset for i in mesh_data['indices']]
                    all_indices.extend(offset_indices)
                    
                    vertex_offset += mesh_data['vertex_count']
                
                # Create merged mesh
                wm.progress_update(80)
                merged_data = {
                    'positions': all_positions,
                    'normals': all_normals,
                    'uvs': all_uvs,
                    'tangents': all_tangents if all_tangents else None,
                    'indices': all_indices,
                    'vertex_count': vertex_offset,
                    'index_count': len(all_indices)
                }
                
                obj = self.create_mesh_from_data(merged_data, "Merged", context)
                created_objects.append(obj)
                
                # Create material (using first block's textures as reference)
                wm.progress_update(90)
                if first_albedo and first_albedo.exists():
                    mat = self.create_material("Merged", str(first_albedo), str(first_normal) if first_normal else None)
                    if mat:
                        obj.data.materials.append(mat)
                        # Assign material to all faces
                        for poly in obj.data.polygons:
                            poly.material_index = 0
                        self.report({'INFO'}, f"Material assigned to merged terrain")
                else:
                    self.report({'ERROR'}, f"Albedo not found: {first_albedo}")
                
            else:
                # Import each block as a separate mesh with proper positioning and unique materials
                total_files = len(block_files)
                
                # Create collection for all terrain blocks
                terrain_collection = bpy.data.collections.get("ROSE_Terrain_Blocks")
                if not terrain_collection:
                    terrain_collection = bpy.data.collections.new("ROSE_Terrain_Blocks")
                    context.scene.collection.children.link(terrain_collection)
                
                for idx, filepath in enumerate(block_files):
                    wm.progress_update(20 + (idx * 60 // total_files))
                    
                    if not filepath.exists():
                        self.report({'WARNING'}, f"File does not exist: {filepath}")
                        continue
                    
                    # Parse block coordinates from filename (e.g., "block_31_30.mesh.bin")
                    stem = filepath.stem
                    if stem.endswith('.mesh'):
                        stem = stem[:-5]  # Remove ".mesh" suffix
                    
                    parts = stem.split('_')
                    block_x, block_y = 0, 0
                    if len(parts) >= 3 and parts[0] == 'block':
                        try:
                            block_x = int(parts[1])
                            block_y = int(parts[2])
                        except ValueError:
                            self.report({'WARNING'}, f"Could not parse coordinates from {stem}")
                    
                    # World position matching the Rust client (zone_loader.rs
                    # 3317-3318, 3424): from_xyz(offset_x - 5200, 0,
                    # -offset_y + 5200), all in meters (the converter emits
                    # meters, like the merge path above - not centimeters).
                    rust_offset_x = 160.0 * block_x
                    rust_offset_y = 160.0 * (65.0 - block_y)

                    # Bevy Transform(x, y=height, z=depth) -> Blender (x, depth, height)
                    world_pos_x = rust_offset_x - 5200.0
                    world_pos_y = -rust_offset_y + 5200.0
                    
                    self.report({'INFO'}, f"Block {stem}: World position ({world_pos_x:.1f}, {world_pos_y:.1f})")
                    
                    # Load mesh data
                    mesh_data = self.load_mesh_binary(str(filepath))
                    
                    albedo_path = filepath.with_name(f"{stem}_albedo.png")
                    normal_path = filepath.with_name(f"{stem}_normal.png")
                    
                    if not albedo_path.exists():
                        self.report({'ERROR'}, f"Albedo texture not found for block {stem}: {albedo_path}")
                        continue
                    
                    # Create mesh object (positioned via object location below)
                    obj = self.create_mesh_from_data(
                        mesh_data,
                        stem,  # Unique name per block
                        context
                    )
                    
                    # Position the block in world space (matching Rust implementation)
                    obj.location = (world_pos_x, world_pos_y, 0.0)
                    
                    # Link to collection instead of default ROSE_Terrain
                    terrain_collection.objects.link(obj)
                    created_objects.append(obj)
                    
                    # Create and assign unique material per block
                    mat = self.create_material(stem, str(albedo_path), str(normal_path))
                    if mat:
                        obj.data.materials.append(mat)
                        for poly in obj.data.polygons:
                            poly.material_index = 0
                        self.report({'INFO'}, f"Block {stem}: Material '{mat.name}' assigned")
                    else:
                        self.report({'ERROR'}, f"Failed to create material for block {stem}")
            
            wm.progress_update(95)
            
            # Restore viewport updates
            try:
                bpy.context.preferences.view.use_auto_persist = original_use_autopersist
            except:
                pass
            
            elapsed = time.time() - start_time
            self.report({'INFO'}, f"Imported {len(created_objects)} object(s) in {elapsed:.2f}s")
            
            return {'FINISHED'}
            
        except Exception as e:
            import traceback
            self.report({'ERROR'}, f"Import failed: {str(e)}")
            self.report({'ERROR'}, traceback.format_exc())
            return {'CANCELLED'}


def menu_func(self, context):
    self.layout.operator(ImportConvertedTerrain.bl_idname, text="Converted ROSE Terrain (.mesh.bin)")


def register():
    bpy.utils.register_class(ImportConvertedTerrain)


def unregister():
    bpy.utils.unregister_class(ImportConvertedTerrain)


if __name__ == "__main__":
    register()